### ISSUE TITLE
Animation speed consideration when implementing the future Animation Update

### ISSUE THREAD

**Issue by DieterKosken** [BlitzKraig/fvtt-DancingLights#1]
Hi, 

Nice mod. Can we get a slider for fire animation speed? or maybe 3 fire "types" in the drop down with different speeds?

**Comment by BlitzKraig** [comment]
Hi Dieter,

There is an animation speed slider already in there, but it's not great. It currently skips frames to slow down the animation (alpha only)

The 'movement' of the fire is not affected by this at the moment. However, I just released v1.1.0 that will let you tweak how much the fire moves, which may help slightly.

I am considering my options for improving the fire animation at the moment, so I will make sure to take animation speed variability into account! :)

**Comment by DieterKosken** [comment]
I just downloaded the update and its great. I will be using this for all my ambient lights. Thanks!

**Comment by BlitzKraig** [comment]
Reopening for further animation speed improvements
