### ISSUE TITLE
Document Foundry VTT 0.7.x Compatibility

### ISSUE THREAD

**Issue by mikelococo** [BlitzKraig/fvtt-DancingLights#10]
With the GA release of Foundry 0.7.5, is it possible to have an update of the readme in the repo and of the description at https://foundryvtt.com/packages/DancingLights/ to reflect the current plans relative to 0.7.x compatibility?

Unfortunately, it's incredibly common for Foundry modules that are fully compatible with the latest release of Foundry VTT to fail to update their module.json file, which means when there is a real instance of incompatibility it's helpful to identify it clearly in the docs. I see that there is a [message on startup](https://github.com/BlitzKraig/fvtt-DancingLights/commit/dfa5715278c021f06e9151c8ee8625f5076b53f6#diff-b1be31f3ac9ecdd58dd6717e9737d113d6535b976dea1087e81119c75aa35e07R1368) when running on incompatible Foundry versions, but it would be helpful to learn that information prior to installation.

**Comment by BlitzKraig** [comment]
Hi mike,
I have updated the description on Foundry, but do not plan to update the repository, as I'll need to make further changes to prevent it from automatically running a build.

With the update description in Foundry, and the message when loading in 0.7 with the module active, I think that should be enough for anyone to realise that the module is no longer supported.

Thanks for your feedback!
