### ISSUE TITLE
Add color-array based blinking and fading lights

### ISSUE THREAD

**Issue by Princess-Cheeseballs** [BlitzKraig/fvtt-DancingLights#2]
Is it possible that you could add a type of dynamic light that switches between multiple different colors like blink does, but in a way that only requires one light source.

**Comment by BlitzKraig** [comment]
Hi Pronana.

I tried to get to this earlier, but GitHub has been having some issues this morning.

Do you mean like a sort of 'disco light'? Where you could give it an array of colors and it would switch between each one after a short interval?

This is definitely possible, as I played with this idea during testing, but it didn't make it to the initial release.
I will have a think about how to best implement this in regards to user input.

**Comment by Princess-Cheeseballs** [comment]
> 
> 
> Hi Pronana.
> 
> I tried to get to this earlier, but GitHub has been having some issues this morning.
> 
> Do you mean like a sort of 'disco light'? Where you could give it an array of colors and it would switch between each one after a short interval?
> 
> This is definitely possible, as I played with this idea during testing, but it didn't make it to the initial release.
> I will have a think about how to best implement this in regards to user input.

Yeah a Disco light is a better way to describe it.

**Comment by BlitzKraig** [comment]
Hi Pronana.

Release 1.4.0 has a basic implementation of this. At the moment, you can only choose 2 or 3 colors for blinking & fading lights, I hope this is enough.

Note that for the blinking colors, you can check "Blink Color Only" to stop the light from actually turning on and off, and instead just cycle the colors.

I'm still trying to come up with a good way to allow an arbitrary amount of colours, this will be in a future release.

Hope that helps! Thanks for the feedback.
