### ISSUE TITLE
Dancing lights on under token vision?

### ISSUE THREAD

**Issue by DieterKosken** [BlitzKraig/fvtt-DancingLights#3]
Would this maybe be available for the light source on the tokens?

**Comment by BlitzKraig** [comment]
I've been thinking about this, and it should be possible, but quite complicated.

I think if I restrict it specifically to the 'Emit Bright' light it should simplify things a bit, and would be good for a player carrying a torch for example.
I'll add it to the list, though it may be some time before I implement this one.

**Comment by BlitzKraig** [comment]
Done in 2.0.0
