### ISSUE TITLE
Updated Version No Longer Compatible with DarkerVision Module

### ISSUE THREAD

**Issue by Dumbhuman** [BlitzKraig/fvtt-DancingLights#7]
Prior to updating today, Dancing Lights played nicely with DarkerVision, allowing even flickering dim lights within a character's dim vision radius to appear as bright light.  After the update, even when using a standard light with its Dancing Lights check box unticked, DarkerVision no longer works if the Dancing Lights module is enabled.

Without updated Dancing Lights module enabled:
![image](https://user-images.githubusercontent.com/63615591/88328783-cb5e1200-ccdd-11ea-93c4-e3494453fcde.png)

With updated Dancing Lights module enabled:
![image](https://user-images.githubusercontent.com/63615591/88328856-e7fa4a00-ccdd-11ea-8dec-8d5fd8441f10.png)

**Comment by Dumbhuman** [comment]
Is there a way I can roll back my update locally and install version 1.51 again?  I have a game in two days for which I'd love to have both fire flicker and more proper darkvision enabled.

**Comment by BlitzKraig** [comment]
Hi Dumbhuman,

In the latest DL version, we both override the same method, and the way I've done it clobbers his module a bit.

I've added support for the module in 2.0.4
