### ISSUE TITLE
Token Config does not Scroll

### ISSUE THREAD

**Issue by QuelessQuest** [BlitzKraig/fvtt-DancingLights#8]
When attempting to configure a Token with Dancing Lights, the window will not scroll to be able to view and save the options.

Browser: Chrome, latest version
OS: Mac OS 10.15.5

![image](https://user-images.githubusercontent.com/2728882/88407948-e0e84000-cda0-11ea-82ba-c7933a8c3491.png)

**Comment by BlitzKraig** [comment]
Hi QuelessQuest,

I am unable to reproduce this. Are you using some sort of UI overhaul module that could be interfering? It looks a little different from my tests I've just run on a mac.

Thanks

**Comment by BlitzKraig** [comment]
Hi QuelessQuest,

I worked out you're using Ernie's Modern UI.

I installed the module and tested, and was able to reproduce the issue.
I've added support for Ernie's in 2.0.5, please give it a try.

Thanks for your feedback
