### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [BlitzKraig/fvtt-DancingLights#9]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by BlitzKraig** [comment]
Hi lozalojo!

My newer modules are translatable. Dancing Lights likely won't have translation support added, as it will be deprecated once Foundry 0.7.x is stable, in favour of my new lighting module.

Thanks for the feedback!
